#!/usr/bin/env python3
from __future__ import annotations

import shutil
import time
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
SKILLS = REPO / "skills"
RELEASE_ROOT = SKILLS / "release"

IGNORE_NAMES = {
    ".DS_Store",
    "__pycache__",
    "node_modules",
}


def _ignore(_dir: str, names: list[str]) -> set[str]:
    return {n for n in names if n in IGNORE_NAMES}


def copy_skill(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=_ignore)


def remove_path(path: Path) -> None:
    if not path.exists():
        return
    if path.is_dir():
        last_err: Exception | None = None
        for _ in range(3):
            try:
                shutil.rmtree(path)
                return
            except OSError as err:
                last_err = err
                time.sleep(0.05)
        if path.exists() and last_err is not None:
            raise last_err
    else:
        path.unlink(missing_ok=True)


def main() -> int:
    zh_root = RELEASE_ROOT / "skills-zh"
    en_root = RELEASE_ROOT / "skills-en"
    for root in (zh_root, en_root):
        root.mkdir(parents=True, exist_ok=True)

    # fresh rebuild for deterministic release output
    for root in (zh_root, en_root):
        for child in list(root.iterdir()):
            remove_path(child)

    for section in ("testing-types", "testing-workflows"):
        src_section = SKILLS / section
        if not src_section.exists():
            continue
        zh_section = zh_root / section
        en_section = en_root / section
        zh_section.mkdir(parents=True, exist_ok=True)
        en_section.mkdir(parents=True, exist_ok=True)

        for skill_dir in sorted([p for p in src_section.iterdir() if p.is_dir()]):
            if skill_dir.name in {"skills-zh", "skills-en", "release"}:
                continue
            # Keep language-specific canonical placement:
            # - zh skills in skills-zh
            # - en skills in skills-en
            if skill_dir.name.endswith("-en"):
                copy_skill(skill_dir, en_section / skill_dir.name)
            else:
                copy_skill(skill_dir, zh_section / skill_dir.name)

            # Compatibility copies:
            # Some prompt files reference counterpart language directories
            # (e.g. ../../functional-testing/prompts/*.md or ../../functional-testing-en/prompts/*_EN.md).
            # Keep these links resolvable inside each release root.
            copy_skill(skill_dir, zh_section / skill_dir.name)
            copy_skill(skill_dir, en_section / skill_dir.name)

    (zh_root / "README.md").write_text(
        "# skills-zh release\n\n"
        "Chinese-first release build (includes counterpart directories for internal link compatibility).\n"
        "Generated by `scripts/build_release_skill_dirs.py`.\n",
        encoding="utf-8",
    )
    (en_root / "README.md").write_text(
        "# skills-en release\n\n"
        "English-first release build (includes counterpart directories for internal link compatibility).\n"
        "Generated by `scripts/build_release_skill_dirs.py`.\n",
        encoding="utf-8",
    )

    print(f"release_root={RELEASE_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
