#!/usr/bin/env python3
"""Generate bilingual Skill Composition Catalog and Router-local references."""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

try:
    from .validate_skill_composition import (
        MANIFEST_RELATIVE_PATH,
        load_manifest,
        validate_manifest,
    )
except ImportError:  # pragma: no cover - direct script execution
    from validate_skill_composition import (  # type: ignore
        MANIFEST_RELATIVE_PATH,
        load_manifest,
        validate_manifest,
    )


RELATION_LABELS = {
    "zh": {
        "precedes": "先于",
        "recommended_with": "推荐组合",
        "alternative_to": "可替代",
        "conflicts_with": "冲突",
    },
    "en": {
        "precedes": "precedes",
        "recommended_with": "recommended with",
        "alternative_to": "alternative to",
        "conflicts_with": "conflicts with",
    },
}
OUTPUTS = {
    "zh_reference": Path("skills/zh/testing-workflows/discover-testing/reference.md"),
    "en_reference": Path("skills/en/testing-workflows/discover-testing/reference.md"),
    "zh_catalog": Path("docs/catalog/skills-composition.md"),
    "en_catalog": Path("docs/catalog/skills-composition_EN.md"),
}


def _localized(value: dict[str, Any], language: str) -> Any:
    return value[language]


def _skill_relative_path(repo_root: Path, language: str, slug: str) -> str:
    language_root = repo_root / "skills" / language
    matches = sorted(
        path
        for path in language_root.glob("*/*")
        if path.is_dir() and path.name == slug and (path / "SKILL.md").is_file()
    )
    if not matches:
        return f"skills/{language}/<missing>/{slug}"
    return matches[0].relative_to(repo_root).as_posix()


def _bullet_lines(values: list[str], indent: str = "  ") -> list[str]:
    return [f"{indent}- {value}" for value in values]


def render_router_reference(manifest: dict[str, Any], language: str) -> str:
    """Render a self-contained reference that can travel with discover-testing."""
    zh = language == "zh"
    if zh:
        lines = [
            "# discover-testing 路由参考",
            "",
            "> 此文件由 `scripts/generate_skill_composition_views.py` 生成。它是 Router Skill 的本地、自包含参考，不依赖仓库外部文件，也不把组合关系变成安装依赖。",
            "",
            "## 使用边界",
            "",
            "- 先根据用户目标选择一条最匹配的路线。",
            "- 每条路线只给一个主 Skill，可选 Skill 最多一个；不要输出菜单式候选列表。",
            "- 信息不足时保留假设和证据缺口；本参考不证明模型、运行时或业务效果。",
            "",
            "## Routes",
            "",
        ]
    else:
        lines = [
            "# discover-testing Router Reference",
            "",
            "> Generated by `scripts/generate_skill_composition_views.py`. This is a self-contained local reference for the Router Skill; it has no repository-outside file dependency and does not turn composition into an installation dependency.",
            "",
            "## Boundaries",
            "",
            "- Select the single route that best matches the user's goal.",
            "- Return one primary Skill and at most one optional Skill; do not emit a menu of candidates.",
            "- Preserve assumptions and evidence gaps when information is incomplete; this reference does not prove model, runtime, or business effectiveness.",
            "",
            "## Routes",
            "",
        ]

    for route in manifest["routes"]:
        label = _localized(route["label"], language)
        intent = _localized(route["intent"], language)
        phase = _localized(route["phase"], language)
        handoff = _localized(route["handoff"], language)
        not_for = _localized(route["not_for"], language)
        optional = route.get("optional") or ("无" if zh else "none")
        lines.extend(
            [
                f"### {label} (`{route['id']}`)",
                "",
                f"- {'触发意图' if zh else 'Intent'}: {intent}",
                f"- {'适用阶段' if zh else 'Applicable phase'}: {phase}",
                f"- {'主 Skill' if zh else 'Primary Skill'}: `{route['primary']}`",
                f"- {'可选 Skill' if zh else 'Optional Skill'}: `{optional}`" if route.get("optional") else f"- {'可选 Skill' if zh else 'Optional Skill'}: {optional}",
                f"- {'交接' if zh else 'Handoff'}: {handoff}",
                f"- {'不适用' if zh else 'Not for'}:",
            ]
        )
        lines.extend(_bullet_lines(not_for))
        lines.append("")

    if zh:
        lines.extend(
            [
                "## 选择后的交接",
                "",
                "输出路由理由、关键假设、证据缺口和下一步交接输入；组合建议是导航信息，不是强制执行链。",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "## Handoff after selection",
                "",
                "State the routing reason, key assumptions, evidence gaps, and next handoff input; composition is navigation, not a mandatory execution chain.",
                "",
            ]
        )
    return "\n".join(lines)


def render_catalog(manifest: dict[str, Any], repo_root: Path, language: str) -> str:
    """Render the full repository-facing route and relation view."""
    zh = language == "zh"
    if zh:
        lines = [
            "<!-- Generated by scripts/generate_skill_composition_views.py; do not edit manually. -->",
            "",
            '<div align="right"><strong>🇨🇳 中文</strong> | <a href="./skills-composition_EN.md">🇬🇧 English</a></div>',
            "",
            "# Skill Composition Catalog",
            "",
            "此 Catalog 由 `docs/governance/skill-composition.yaml` 生成，记录路线导航和组合建议，不表达安装依赖、运行时编排或质量评分。Router 的独立安装参考位于自身目录的 `reference.md`。",
            "",
            "## Routes / Recipes",
            "",
            "| Route | 适用阶段 | 主 Skill（目录） | 可选 Skill（目录） | 不适用 |",
            "| --- | --- | --- | --- | --- |",
        ]
    else:
        lines = [
            "<!-- Generated by scripts/generate_skill_composition_views.py; do not edit manually. -->",
            "",
            '<div align="right"><a href="./skills-composition.md">🇨🇳 Chinese</a> | <strong>🇬🇧 English</strong></div>',
            "",
            "# Skill Composition Catalog",
            "",
            "Generated from `docs/governance/skill-composition.yaml`. It records route navigation and composition suggestions, not installation dependencies, runtime orchestration, or quality scores. The Router's independent-install reference lives in its own `reference.md`.",
            "",
            "## Routes / Recipes",
            "",
            "| Route | Applicable phase | Primary Skill (path) | Optional Skill (path) | Not for |",
            "| --- | --- | --- | --- | --- |",
        ]

    for route in manifest["routes"]:
        primary_path = _skill_relative_path(repo_root, language, route["primary"])
        optional = route.get("optional")
        optional_cell = (
            f"`{optional}` (`{_skill_relative_path(repo_root, language, optional)}`)" if optional else ("无" if zh else "none")
        )
        not_for = "; ".join(_localized(route["not_for"], language))
        lines.append(
            f"| `{route['id']}` — {_localized(route['label'], language)} | {_localized(route['phase'], language)} | `{route['primary']}` (`{primary_path}`) | {optional_cell} | {not_for} |"
        )

    if zh:
        lines.extend(
            [
                "",
                "## Relations",
                "",
                "关系只用于导航，不表示 Skill A 会自动安装或调用 Skill B。",
                "",
                "| From | 关系 | To |",
                "| --- | --- | --- |",
            ]
        )
    else:
        lines.extend(
            [
                "",
                "## Relations",
                "",
                "Relations are navigation metadata; they do not mean Skill A installs or automatically calls Skill B.",
                "",
                "| From | Relation | To |",
                "| --- | --- | --- |",
            ]
        )
    for relation in manifest["relations"]:
        relation_label = RELATION_LABELS[language][relation["type"]]
        lines.append(f"| `{relation['from']}` | {relation_label} | `{relation['to']}` |")

    lines.extend(
        [
            "",
            "## Reproduce",
            "",
            "```bash",
            "python3 scripts/validate_skill_composition.py --repo-root .",
            "python3 scripts/generate_skill_composition_views.py --repo-root . --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def output_contents(repo_root: Path, manifest: dict[str, Any]) -> dict[Path, str]:
    return {
        repo_root / OUTPUTS["zh_reference"]: render_router_reference(manifest, "zh"),
        repo_root / OUTPUTS["en_reference"]: render_router_reference(manifest, "en"),
        repo_root / OUTPUTS["zh_catalog"]: render_catalog(manifest, repo_root, "zh"),
        repo_root / OUTPUTS["en_catalog"]: render_catalog(manifest, repo_root, "en"),
    }


def load_and_validate(repo_root: Path, manifest_path: Path | None = None) -> dict[str, Any]:
    path = manifest_path or repo_root / MANIFEST_RELATIVE_PATH
    manifest = load_manifest(path)
    errors = validate_manifest(manifest, repo_root)
    if errors:
        raise ValueError("\n".join(errors))
    return manifest


def stale_outputs(repo_root: Path, manifest_path: Path | None = None) -> list[str]:
    manifest = load_and_validate(repo_root, manifest_path)
    stale: list[str] = []
    for path, expected in output_contents(repo_root, manifest).items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(path.relative_to(repo_root).as_posix())
    return stale


def generate_views(repo_root: Path, manifest_path: Path | None = None) -> list[str]:
    manifest = load_and_validate(repo_root, manifest_path)
    generated: list[str] = []
    for path, content in output_contents(repo_root, manifest).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        generated.append(path.relative_to(repo_root).as_posix())
    return generated


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--manifest", type=Path, default=None)
    parser.add_argument("--check", action="store_true", help="fail if generated views are stale")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    repo_root = args.repo_root.resolve()
    manifest_path = args.manifest.resolve() if args.manifest else None
    try:
        if args.check:
            stale = stale_outputs(repo_root, manifest_path)
            if stale:
                print("stale_composition_views=" + ",".join(stale))
                return 1
            print("composition_views=up-to-date")
            return 0
        for relative in generate_views(repo_root, manifest_path):
            print(f"generated={relative}")
        return 0
    except (OSError, ValueError) as error:
        print(f"composition_generation_error={error}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
