#!/usr/bin/env python3
"""Generate the physical Skill inventory used by the governance matrix."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SECTIONS = ("testing-types", "testing-workflows", "skill-engineering")


def discover() -> list[tuple[str, str, str]]:
    rows = []
    for language in ("zh", "en"):
        for section in SECTIONS:
            root = ROOT / "skills" / language / section
            for directory in sorted(root.iterdir() if root.exists() else []):
                if directory.is_dir() and (directory / "SKILL.md").exists():
                    rows.append((directory.name, language, section))
    return rows


def main() -> None:
    rows = discover()
    zh = sum(language == "zh" for _, language, _ in rows)
    en = sum(language == "en" for _, language, _ in rows)
    output = [
        '<div align="right"><strong>Snapshot</strong> | Generated by `python3 scripts/generate_skill_inventory.py`</div>',
        "",
        "# Skill Inventory",
        "",
        f"> Snapshot scope: {zh} Chinese and {en} English Skill directories. This records verifiable filesystem structure only; it does not assert virtual Domain, Capability Match, quality score, or runtime effectiveness.",
        "",
        "| Skill | Language | Physical category | Required artifact contract |",
        "| --- | --- | --- | --- |",
    ]
    output.extend(f"| `{skill}` | {language} | {section} | `SKILL.md` / `prompts/` / `agents/openai.yaml` / `evals/` |" for skill, language, section in rows)
    (ROOT / "docs/generated/skill-inventory.md").write_text("\n".join(output) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
